services:
  barajitas-backend:
    image: backend-barajitas
    ports:
      - 8080:8080
    build: backend/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgresql://ci5644user:ci5644redteam@host.docker.internal:5433/TestHerrWeb
      - PGHOST=postgres
    healthcheck:
      test: "curl -I localhost:8080/ | grep HTTP/1.1 || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    network_mode: "host"
  
  barajitas-frontend:
    image: frontend-barajitas
    ports:
      - 3000:3000
    build: frontend/
    depends_on:
      barajitas-backend:
        condition: service_healthy
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: 'host'
    
networks:
  barajitas-network:
    ipam:
      driver: default
