INSERT INTO card (name, player_position, player_number, country, photo_url) VALUES
('Marc-André Ter Stegen', 'GOALKEEPER', 22, 'Germany', '/cards/Marc-André Ter Stegen.jpg'),
('Thilo Kehrer', 'DEFENDER', 5, 'Germany', '/cards/Thilo Kehrer.jpg'),
('Antonio Rüdiger', 'DEFENDER', 2, 'Germany', '/cards/Antonio Rüdiger.jpg'),
('David Raum', 'DEFENDER', 3, 'Germany', '/cards/David Raum.jpg'),
('Robin Gosens', 'DEFENDER', 19, 'Germany', '/cards/Robin Gosens.jpg'),
('Joshua Kimmich', 'MIDFIELDER', 6, 'Germany', '/cards/Joshua Kimmich.jpg'),
('Leon Goretzka', 'MIDFIELDER', 8, 'Germany', '/cards/Leon Goretzka.jpg'),
('Jonas Hofmann', 'MIDFIELDER', 18, 'Germany', '/cards/Jonas Hofmann.jpg'),
('Kai Havertz', 'FORWARD', 7, 'Germany', '/cards/Kai Havertz.jpg'),
('Marco Reus', 'FORWARD', 11, 'Germany', '/cards/Marco Reus.jpg'),
('Thomas Müller', 'FORWARD', 13, 'Germany', '/cards/Thomas Müller.jpg'),
('Mike Maignan', 'GOALKEEPER', 16, 'France', '/cards/Mike Maignan.jpg'),
('Benjamin Pavard', 'DEFENDER', 2, 'France', '/cards/Benjamin Pavard.jpg'),
('Jules Koundé', 'DEFENDER', 5, 'France', '/cards/Jules Koundé.jpg'),
('Raphaël Varane', 'DEFENDER', 4, 'France', '/cards/Raphaël Varane.jpg'),
('Theo Hernández', 'DEFENDER', 22, 'France', '/cards/Theo Hernández.jpg'),
('Aurélien Tchouaméni', 'MIDFIELDER', 8, 'France', '/cards/Aurélien Tchouaméni.jpg'),
('N\'Golo Kanté', 'MIDFIELDER', 13, 'France', '/cards/N\'Golo Kanté.jpg'),
('Adrien Rabiot', 'MIDFIELDER', 14, 'France', '/cards/Adrien Rabiot.jpg'),
('Antoine Griezmann', 'FORWARD', 7, 'France', '/cards/Antoine Griezmann.jpg'),
('Karim Benzema', 'FORWARD', 19, 'France', '/cards/Karim Benzema.jpg'),
('Kylian Mbappé', 'FORWARD', 10, 'France', '/cards/Kylian Mbappé.jpg'),
('Alisson', 'GOALKEEPER', 1, 'Brazil', '/cards/Alisson.jpg'),
('Éder Militão', 'DEFENDER', 14, 'Brazil', '/cards/Éder Militão.jpg'),
('Thiago Silva', 'DEFENDER', 3, 'Brazil', '/cards/Thiago Silva.jpg'),
('Marquinhos', 'DEFENDER', 4, 'Brazil', '/cards/Marquinhos.jpg'),
('Fred', 'MIDFIELDER', 8, 'Brazil', '/cards/Fred.jpg'),
('Casemiro', 'MIDFIELDER', 5, 'Brazil', '/cards/Casemiro.jpg'),
('Lucas Paquetá', 'MIDFIELDER', 7, 'Brazil', '/cards/Lucas Paquetá.jpg'),
('Neymar Jr', 'FORWARD', 10, 'Brazil', '/cards/Neymar Jr.jpg'),
('Gabriel Jesus', 'FORWARD', 18, 'Brazil', '/cards/Gabriel Jesus.jpg'),
('Richarlison', 'FORWARD', 9, 'Brazil', '/cards/Richarlison.jpg'),
('Vinícius Jr', 'FORWARD', 20, 'Brazil', '/cards/Vinícius Jr.jpg'),
('Rui Patricio', 'GOALKEEPER', 1, 'Portugal', '/cards/Rui Patricio.jpg'),
('Nuno Mendes', 'DEFENDER', 19, 'Portugal', '/cards/Nuno Mendes.jpg'),
('Pepe', 'DEFENDER', 3, 'Portugal', '/cards/Pepe.jpg'),
('Rúben Dias', 'DEFENDER', 4, 'Portugal', '/cards/Rúben Dias.jpg'),
('João Cancelo', 'DEFENDER', 20, 'Portugal', '/cards/João Cancelo.jpg'),
('Danilo Pereira', 'MIDFIELDER', 13, 'Portugal', '/cards/Danilo Pereira.jpg'),
('João Moutinho', 'MIDFIELDER', 8, 'Portugal', '/cards/João Moutinho.jpg'),
('Bruno Fernandes', 'MIDFIELDER', 11, 'Portugal', '/cards/Bruno Fernandes.jpg'),
('Bernardo Silva', 'MIDFIELDER', 10, 'Portugal', '/cards/Bernardo Silva.jpg'),
('Diogo Jota', 'FORWARD', 21, 'Portugal', '/cards/Diogo Jota.jpg'),
('Cristiano Ronaldo', 'FORWARD', 7, 'Portugal', '/cards/Cristiano Ronaldo.jpg'),
('Emiliano Martínez', 'GOALKEEPER', 23, 'Argentina', '/cards/Emiliano Martínez.jpg'),
('Nahuel Molina', 'DEFENDER', 26, 'Argentina', '/cards/Nahuel Molina.jpg'),
('Germán Pezzella', 'DEFENDER', 6, 'Argentina', '/cards/Germán Pezzella.jpg'),
('Cristian Romero', 'DEFENDER', 13, 'Argentina', '/cards/Cristian Romero.jpg'),
('Marcos Acuña', 'DEFENDER', 8, 'Argentina', '/cards/Marcos Acuña.jpg'),
('Rodrigo De Paul', 'MIDFIELDER', 7, 'Argentina', '/cards/Rodrigo De Paul.jpg'),
('Leandro Paredes', 'MIDFIELDER', 5, 'Argentina', '/cards/Leandro Paredes.jpg'),
('Ángel Di María', 'MIDFIELDER', 11, 'Argentina', '/cards/Ángel Di María.jpg'),
('Alejandro Gómez', 'FORWARD', 17, 'Argentina', '/cards/Alejandro Gómez.jpg'),
('Julián Álvarez', 'FORWARD', 9, 'Argentina', '/cards/Julián Álvarez.jpg'),
('Lionel Messi', 'FORWARD', 10, 'Argentina', '/cards/Lionel Messi.jpg'),
('Jordan Pickford', 'GOALKEEPER', 1, 'England', '/cards/Jordan Pickford.jpg'),
('Trent Alexander-Arnold', 'DEFENDER', 18, 'England', '/cards/Trent Alexander-Arnold.jpg'),
('Kyle Walker', 'DEFENDER', 2, 'England', '/cards/Kyle Walker.jpg'),
('John Stones', 'DEFENDER', 5, 'England', '/cards/John Stones.jpg'),
('Luke Shaw', 'DEFENDER', 3, 'England', '/cards/Luke Shaw.jpg'),
('Declan Rice', 'MIDFIELDER', 4, 'England', '/cards/Declan Rice.jpg'),
('Jack Grealish', 'MIDFIELDER', 7, 'England', '/cards/Jack Grealish.jpg'),
('Jude Bellingham', 'MIDFIELDER', 10, 'England', '/cards/Jude Bellingham.jpg'),
('Phil Foden', 'FORWARD', 20, 'England', '/cards/Phil Foden.jpg'),
('Harry Kane', 'FORWARD', 9, 'England', '/cards/Harry Kane.jpg'),
('Bukayo Saka', 'FORWARD', 17, 'England', '/cards/Bukayo Saka.jpg'),
('Dominik Livaković', 'GOALKEEPER', 1, 'Croatia', '/cards/Dominik Livaković.jpg'),
('Joško Gvardiol', 'DEFENDER', 20, 'Croatia', '/cards/Joško Gvardiol.jpg'),
('Josip Juranović', 'DEFENDER', 22, 'Croatia', '/cards/Josip Juranović.jpg'),
('Duje Ćaleta-Car', 'DEFENDER', 5, 'Croatia', '/cards/Duje Ćaleta-Car.jpg'),
('Dejan Lovren', 'DEFENDER', 6, 'Croatia', '/cards/Dejan Lovren.jpg'),
('Ivan Perišić', 'MIDFIELDER', 4, 'Croatia', '/cards/Ivan Perišić.jpg'),
('Mateo Kovaćić', 'MIDFIELDER', 8, 'Croatia', '/cards/Mateo Kovaćić.jpg'),
('Marcelo Brozović', 'MIDFIELDER', 11, 'Croatia', '/cards/Marcelo Brozović.jpg'),
('Luka Modrić', 'MIDFIELDER', 10, 'Croatia', '/cards/Luka Modrić.jpg'),
('Andrej Kramarić', 'FORWARD', 9, 'Croatia', '/cards/Andrej Kramarić.jpg'),
('Mislav Oršić', 'FORWARD', 18, 'Croatia', '/cards/Mislav Oršić.jpg'),
('Thibaut Courtois', 'GOALKEEPER', 1, 'Belgium', '/cards/Thibaut Courtois.jpg'),
('Thomas Meunier', 'DEFENDER', 15, 'Belgium', '/cards/Thomas Meunier.jpg'),
('Jan Vertonghen', 'DEFENDER', 5, 'Belgium', '/cards/Jan Vertonghen.jpg'),
('Toby Alderweireld', 'DEFENDER', 2, 'Belgium', '/cards/Toby Alderweireld.jpg'),
('Timothy Castagne', 'DEFENDER', 21, 'Belgium', '/cards/Timothy Castagne.jpg'),
('Youri Tielemans', 'MIDFIELDER', 8, 'Belgium', '/cards/Youri Tielemans.jpg'),
('Charles De Ketelaere', 'MIDFIELDER', 22, 'Belgium', '/cards/Charles De Ketelaere.jpg'),
('Kevin De Bruyne', 'MIDFIELDER', 7, 'Belgium', '/cards/Kevin De Bruyne.jpg'),
('Dries Mertens', 'FORWARD', 14, 'Belgium', '/cards/Dries Mertens.jpg'),
('Romelu Lukaku', 'FORWARD', 9, 'Belgium', '/cards/Romelu Lukaku.jpg'),
('Eden Hazard', 'FORWARD', 10, 'Belgium', '/cards/Eden Hazard.jpg');
