INSERT INTO card (name, player_position, player_number, country, photo_url) VALUES
('Lionel Messi', 'FORWARD', 10, 'Argentina', '/cards/Lionel Messi.jpeg'),
('Cristiano Ronaldo', 'FORWARD', 7, 'Portugal', '/cards/Cristiano Ronaldo.jpeg'),
('Neymar Jr', 'FORWARD', 10, 'Brazil', '/cards/Neymar Jr.jpeg'),
('Kylian Mbappé', 'FORWARD', 10, 'France', '/cards/Kylian Mbappé.jpeg'),
('Kevin De Bruyne', 'MIDFIELDER', 7, 'Belgium', '/cards/Kevin De Bruyne.jpeg'),
('Virgil van Dijk', 'DEFENDER', 4, 'Netherlands', '/cards/Virgil Van Dijk.jpeg'),
('Sadio Mané', 'FORWARD', 10, 'Senegal', '/cards/Sadio Mané.jpeg'),
('Harry Kane', 'FORWARD', 9, 'England', '/cards/Harry Kane.jpeg'),
('Luka Modrić', 'MIDFIELDER', 10, 'Croatia', '/cards/Luka Modrić.jpeg'),
('Robert Lewandowski', 'FORWARD', 9, 'Poland', '/cards/Robert Lewandowski.jpeg'),
('Eden Hazard', 'FORWARD', 7, 'Belgium', '/cards/Eden Hazard.jpeg'),
('Paul Pogba', 'MIDFIELDER', 6, 'France', '/cards/Paul Pogba.jpeg'),
('Alisson Becker', 'GOALKEEPER', 1, 'Brazil', '/cards/Alisson.jpeg'),
('Raheem Sterling', 'FORWARD', 10, 'England', '/cards/Raheem Sterling.jpeg'),
('Antoine Griezmann', 'FORWARD', 7, 'France', '/cards/Antoine Griezmann.jpeg'),
('Frenkie de Jong', 'MIDFIELDER', 21, 'Netherlands', '/cards/Frenkie De Jong.jpeg'),
('Romelu Lukaku', 'FORWARD', 9, 'Belgium', '/cards/Romelu Lukaku.jpeg'),
('Thiago Silva', 'DEFENDER', 2, 'Brazil', '/cards/Thiago Silva.jpeg'),
('Luis Suárez', 'FORWARD', 9, 'Uruguay', '/cards/Luis Suárez.jpeg'),
('Angel Di Maria', 'FORWARD', 11, 'Argentina', '/cards/Angel Di María.jpeg'),
('Manuel Neuer', 'GOALKEEPER', 1, 'Germany', '/cards/Manuel Neuer.jpeg'),
('Gareth Bale', 'FORWARD', 11, 'Wales', '/cards/Gareth Bale.jpeg'),
('Sergio Busquets', 'MIDFIELDER', 5, 'Spain', '/cards/Sergio Busquets.jpeg'),
('Memphis Depay', 'FORWARD', 10, 'Netherlands', '/cards/Memphis Depay.jpeg'),
('Milan Borjan', 'GOALKEEPER', 18, 'Canada', '/cards/Milan Borjan.jpeg'),
('Joshua Kimmich', 'MIDFIELDER', 6, 'Germany', '/cards/Joshua Kimmich.jpeg'),
('Hugo Lloris', 'GOALKEEPER', 1, 'France', '/cards/Hugo Lloris.jpeg'),
('Marquinhos', 'DEFENDER', 5, 'Brazil', '/cards/Marquinhos.jpeg'),
('Heung-min Son', 'FORWARD', 7, 'South Korea', '/cards/Heung-Min Son.jpeg'),
('Rúben Dias', 'DEFENDER', 3, 'Portugal', '/cards/Rúben Dias.jpeg'),
('Ederson', 'GOALKEEPER', 23, 'Brazil', '/cards/Ederson.jpeg'),
('Alex Sandro', 'DEFENDER', 12, 'Brazil', '/cards/Alex Sandro.jpeg'),
('Éder Militão', 'DEFENDER', 14, 'Brazil', '/cards/Éder Militão.jpeg'),
('Casemiro', 'MIDFIELDER', 5, 'Brazil', '/cards/Casemiro.jpeg'),
('Vinícius Jr', 'FORWARD', 20, 'Brazil', '/cards/Vinícius Jr.jpeg'),
('Gabriel Jesus', 'FORWARD', 9, 'Brazil', '/cards/Gabriel Jesus.jpeg');