INSERT INTO card (name, player_position, player_number, country, photo_url) VALUES 
('Lionel Messi', 'FORWARD', 10, 'Argentina', 'URL_to_Player_Photo'),
('Cristiano Ronaldo', 'FORWARD', 7, 'Portugal', 'URL_to_Player_Photo'),
('Neymar Jr', 'FORWARD', 10, 'Brazil', 'URL_to_Player_Photo'),
('Kylian Mbappé', 'FORWARD', 10, 'France', 'URL_to_Player_Photo'),
('Kevin De Bruyne', 'MIDFIELDER', 7, 'Belgium', 'URL_to_Player_Photo'),
('Virgil van Dijk', 'DEFENDER', 4, 'Netherlands', 'URL_to_Player_Photo'),
('Sadio Mané', 'FORWARD', 10, 'Senegal', 'URL_to_Player_Photo'),
('Harry Kane', 'FORWARD', 9, 'England', 'URL_to_Player_Photo'),
('Luka Modrić', 'MIDFIELDER', 10, 'Croatia', 'URL_to_Player_Photo'),
('Robert Lewandowski', 'FORWARD', 9, 'Poland', 'URL_to_Player_Photo'),
('Eden Hazard', 'FORWARD', 7, 'Belgium', 'URL_to_Player_Photo'),
('Paul Pogba', 'MIDFIELDER', 6, 'France', 'URL_to_Player_Photo'),
('Alisson Becker', 'GOALKEEPER', 1, 'Brazil', 'URL_to_Player_Photo'),
('Raheem Sterling', 'FORWARD', 10, 'England', 'URL_to_Player_Photo'),
('Antoine Griezmann', 'FORWARD', 7, 'France', 'URL_to_Player_Photo'),
('Frenkie de Jong', 'MIDFIELDER', 21, 'Netherlands', 'URL_to_Player_Photo'),
('Romelu Lukaku', 'FORWARD', 9, 'Belgium', 'URL_to_Player_Photo'),
('Thiago Silva', 'DEFENDER', 2, 'Brazil', 'URL_to_Player_Photo'),
('Luis Suárez', 'FORWARD', 9, 'Uruguay', 'URL_to_Player_Photo'),
('Angel Di Maria', 'FORWARD', 11, 'Argentina', 'URL_to_Player_Photo'),
('Manuel Neuer', 'GOALKEEPER', 1, 'Germany', 'URL_to_Player_Photo'),
('Gareth Bale', 'FORWARD', 11, 'Wales', 'URL_to_Player_Photo'),
('Sergio Busquets', 'MIDFIELDER', 5, 'Spain', 'URL_to_Player_Photo'),
('Memphis Depay', 'FORWARD', 10, 'Netherlands', 'URL_to_Player_Photo'),
('Milan Borjan', 'GOALKEEPER', 18, 'Canada', 'URL_to_Player_Photo'),
('Joshua Kimmich', 'MIDFIELDER', 6, 'Germany', 'URL_to_Player_Photo'),
('Hugo Lloris', 'GOALKEEPER', 1, 'France', 'URL_to_Player_Photo'),
('Marquinhos', 'DEFENDER', 5, 'Brazil', 'URL_to_Player_Photo'),
('Son Heung-min', 'FORWARD', 7, 'South Korea', 'URL_to_Player_Photo'),
('Rúben Dias', 'DEFENDER', 3, 'Portugal', 'URL_to_Player_Photo');
