auth0:
  audience: { https://barajitas.com }
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-crxb1uekqycez2b5.us.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/TestHerrWeb
    username: ci5644user
    password: ci5644redteam
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 000
    locations: classpath:db/migration
    default-schema: public
    create-schemas: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: health
    web:
      exposure:
        include: health



